// AUTO-GENERATED by zedu-egret-store — do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

export type Contributor = {
  name: string;
};

export const contributors: Contributor[] = [
  { name: "AbdulJaleel AbdulSamad" },
  { name: "Adejumoke Oluwole" },
  { name: "Aisha Abdulkadir Joda" },
  { name: "Akinremi Oluwatoyin Mary" },
  { name: "Babatunde Omojuwa" },
  { name: "Bilkis Oladimeji" },
  { name: "Christiana Mabel Nyuma" },
  { name: "Chukwuebuka Okonta" },
  { name: "Chukwumaeze Henry Chinaemerem" },
  { name: "Ekwere Noble Nathan" },
  { name: "EMMANUEL EFFIONG" },
  { name: "Favour Chinaza" },
  { name: "Fawaz Yusuff" },
  { name: "Godgift Achong" },
  { name: "Ibrahim Sulaimon Opeyemi" },
  { name: "Jalar Jacques" },
  { name: "Jonathan Gomina" },
  { name: "Kafayat Faniran" },
  { name: "Manu Jesse" },
  { name: "Michelle Utomi" },
  { name: "Mutairu Dirisu" },
  { name: "Nduaguba Marcellus" },
  { name: "Okeke Chukwuebuka" },
  { name: "Okolie Chinonso Grace" },
  { name: "Olatunji Mafe" },
  { name: "Olayeni Ibrahim" },
  { name: "Oluboye Adekunle" },
  { name: "Onatade Abdulmajeed Adeyincka" },
  { name: "Precious Nse" },
  { name: "Samson eyitene" },
  { name: "Samuel Olowu" },
  { name: "TIENTCHEU WONSI DILANE" },
  { name: "Victor Tommy Etudor" },
];

export const contributorCount = contributors.length;

export default contributors;
