// AUTO-GENERATED by zedu-egret-store — do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

export type Contributor = {
  name: string;
};

export const contributors: Contributor[] = [
  { name: "AbdulJaleel AbdulSamad" },
  { name: "Chukwuebuka Okonta" },
  { name: "Chukwumaeze Henry Chinaemerem" },
  { name: "Fawaz Yusuff" },
  { name: "Godgift Achong" },
  { name: "Ibrahim Sulaimon Opeyemi" },
  { name: "Michelle Utomi" },
  { name: "Okolie Chinonso Grace" },
  { name: "Oluboye Adekunle" },
  { name: "Precious Nse" },
  { name: "Samson eyitene" },
  { name: "TIENTCHEU WONSI DILANE" },
];

export const contributorCount = contributors.length;

export default contributors;
