// AUTO-GENERATED by zedu-egret-store — do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

export type Contributor = {
  name: string;
};

export const contributors: Contributor[] = [
  { name: "AbdulJaleel AbdulSamad" },
  { name: "Chukwumaeze Henry Chinaemerem" },
];

export const contributorCount = contributors.length;

export default contributors;
