// AUTO-GENERATED by zedu-egret-store - do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

export type Contributor = {
  name: string;
  githubUrl: string;
};

export const contributors: Contributor[] = [
  {
    name: "AbdulJaleel AbdulSamad",
    githubUrl: "https://github.com/TrippleA001",
  },
  { name: "Abdullateef Dauda", githubUrl: "https://github.com/abdul-o" },
  { name: "Adejumoke Oluwole", githubUrl: "https://github.com/jumokeolu" },
  {
    name: "Aisha Abdulkadir Joda",
    githubUrl: "https://github.com/jodaaisha2-blip",
  },
  {
    name: "Akinremi Oluwatoyin Mary",
    githubUrl: "https://github.com/Oluwatoyin-224",
  },
  { name: "Babatunde Omojuwa", githubUrl: "https://github.com/juskins" },
  { name: "Bilkis Oladimeji", githubUrl: "https://github.com/Atete22" },
  { name: "Bolakale Fuad", githubUrl: "https://github.com/bolakale6" },
  { name: "Christiana Mabel Nyuma", githubUrl: "https://github.com/Mabel007" },
  { name: "Chukwuebuka Okonta", githubUrl: "https://github.com/devEbuka" },
  {
    name: "Chukwumaeze Henry Chinaemerem",
    githubUrl: "https://github.com/Henrycalebz0",
  },
  { name: "Dolapo Ewulogbo", githubUrl: "https://github.com/DolapoEwulogbo" },
  { name: "Ekwere Noble Nathan", githubUrl: "https://github.com/ENJ0Y-Labs" },
  {
    name: "Elizabeth Oluwatobi David",
    githubUrl: "https://github.com/apptaster123-hash",
  },
  { name: "EMMANUEL EFFIONG", githubUrl: "https://github.com/Solutionsboxx" },
  {
    name: "Emmanuel Matthew Ekanem",
    githubUrl: "https://github.com/AnalytiqDigital",
  },
  {
    name: "Fatimat Titilayo Mufutau",
    githubUrl: "https://github.com/pharteey/",
  },
  { name: "Favour Chinaza", githubUrl: "https://github.com/favourchinaza110" },
  { name: "Fawaz Yusuff", githubUrl: "https://github.com/flawrrz" },
  { name: "Francis Anyah", githubUrl: "https://github.com/assisi-francis" },
  { name: "Godgift Achong", githubUrl: "https://github.com/giftninho" },
  { name: "Godspower Nwwnkwo", githubUrl: "https://github.com/GODSPE1" },
  {
    name: "Ibrahim Sulaimon Opeyemi",
    githubUrl: "https://github.com/Sulai007",
  },
  { name: "Jalar Jacques", githubUrl: "https://github.com/jalarjacques-gif" },
  { name: "Joanna Tebadda", githubUrl: "https://github.com/JoannaTebadda" },
  { name: "Jonathan Gomina", githubUrl: "https://github.com/jonathan401" },
  { name: "Kafayat Faniran", githubUrl: "https://github.com/KaffyDevelops" },
  { name: "Manu Jesse", githubUrl: "https://github.com/Manu2232" },
  { name: "Michelle Utomi", githubUrl: "https://github.com/michycipher" },
  { name: "Mutairu Dirisu", githubUrl: "https://github.com/mutairudirisu" },
  { name: "Nduaguba Marcellus", githubUrl: "https://github.com/creativemcn" },
  {
    name: "Okeke Chukwuebuka",
    githubUrl: "https://github.com/OKEKE-PRINCEWILL",
  },
  {
    name: "Okolie Chinonso Grace",
    githubUrl: "https://github.com/chinonsograce",
  },
  { name: "Olatunji Mafe", githubUrl: "https://github.com/toondji-ix" },
  { name: "Olayeni Ibrahim", githubUrl: "https://github.com/Oluwa555" },
  { name: "Oluboye Adekunle", githubUrl: "https://github.com/Boyeadelo" },
  {
    name: "Olabanji Bunmie-Omotoye Dave",
    githubUrl: "https://github.com/davex-ai",
  },
  {
    name: "Onatade Abdulmajeed Adeyincka",
    githubUrl: "https://github.com/Spider1201",
  },
  { name: "Precious Nse", githubUrl: "https://github.com/preshnse-code" },
  { name: "Precious Nse Samuel", githubUrl: "https://github.com/EmkaySOL" },
  { name: "Preshnat", githubUrl: "https://github.com/presh27" },
  {
    name: "Rukayyah Ibrahim",
    githubUrl: "https://github.com/iamadoctorforreal",
  },
  { name: "Samson Eyitene", githubUrl: "https://github.com/eyisam" },
  { name: "Samuel Olowu", githubUrl: "https://github.com/samuelolowu-ET-hue" },
  {
    name: "TIENTCHEU WONSI DILANE",
    githubUrl: "https://github.com/TientcheuWonsiDilane",
  },
  { name: "Victor Tommy Etudor", githubUrl: "https://github.com/victoretudor" },
];

export const contributorCount = contributors.length;

export default contributors;
